services:
  web:
    build: .
    container_name: fastapi_web
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
      - /app/__pycache__/  # Exclude __pycache__ if any issues with cache
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Use --reload for auto-reload
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
